version: "3.8"

services:
  redis:
    container_name: redis-wej
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    container_name: nodejs-server
    restart: always
    build: .
    env_file: .env
    ports:
      - 5000:5000
    networks:
      - production-backend
    links:
      - mongo

  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   restart: always
  #   env_file: .env
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  #   networks:
  #     - production-backend
  #   volumes:
  #     - mongodb:/data/db

networks:
  production-backend:
# volumes:
#   mongodb:
