on:
  push:
    branches: [main]

  pull_request:
  # The branches below must be a subset of the branches above
  branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd server/ &&
            git pull &&
            yarn &&
            pm2 kill &&
            pm2 start 'yarn start'
